// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TravelStory
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class UIKitTestPanelData : QFramework.UIPanelData
    {
        public int OnInitCalledCount = 0;

        public int OnOpenCalledCount = 0;

        public int OnShowCalledCount = 0;

        public int OnHideCalledCount = 0;

        public int OnCloseCalledCount = 0;
    }
    
    public partial class UIKitTestPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as UIKitTestPanelData ?? new UIKitTestPanelData();
            // please add init code here

            mData.OnInitCalledCount++;
        }
        
        protected override void OnOpen(QFramework.IUIData uiData)
        {
            mData.OnOpenCalledCount++;
        }
        
        protected override void OnShow()
        {
            mData.OnShowCalledCount++;
        }
        
        protected override void OnHide()
        {
            mData.OnHideCalledCount++;
        }
        
        protected override void OnClose()
        {
            mData.OnCloseCalledCount++;
        }
    }
}
