// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:f2104af5-55a3-4112-a0d3-19f6b32fe032
    public partial class UISectionPanel
    {
        
        public const string NAME = "UISectionPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Button SectionBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button BackBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button SettingBtn;
        
        private UISectionPanelData mPrivateData = null;
        
        public UISectionPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UISectionPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            SectionBtn = null;
            BackBtn = null;
            SettingBtn = null;
            mData = null;
        }
    }
}
