//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class UIHotFixCheckPanel
    {
        
        public const string NAME = "UIHotFixCheckPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text Content;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnUpdate;
        
        [SerializeField()]
        public UnityEngine.UI.Button BtnCancel;
        
        private UIHotFixCheckPanelData mPrivateData = null;
        
        public UIHotFixCheckPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIHotFixCheckPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Content = null;
            BtnUpdate = null;
            BtnCancel = null;
            mData = null;
        }
    }
}
