// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework 
{    
    /// <summary>
    /// Path相关的定义
    /// </summary>
    public class IOEditorPathConfig 
	{
        private const string m_IOGeneratorPath = "PTGameData/Path/Config";
        /// <summary>
        /// 生成路径配置资源的路径
        /// </summary>
        public static string IOGeneratorPath {
            get {
                return "Assets/" + m_IOGeneratorPath;
            }
        }
    }
}
