//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class QFramework_UILevelWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(QFramework.UILevel));
		L.RegVar("AlwayBottom", get_AlwayBottom, null);
		L.RegVar("Bg", get_Bg, null);
		L.RegVar("AnimationUnderPage", get_AnimationUnderPage, null);
		L.RegVar("Common", get_Common, null);
		L.RegVar("AnimationOnPage", get_AnimationOnPage, null);
		L.RegVar("PopUI", get_PopUI, null);
		L.RegVar("Guide", get_Guide, null);
		L.RegVar("Const", get_Const, null);
		L.RegVar("Toast", get_Toast, null);
		L.RegVar("Forward", get_Forward, null);
		L.RegVar("AlwayTop", get_AlwayTop, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<QFramework.UILevel>.Check = CheckType;
		StackTraits<QFramework.UILevel>.Push = Push;
	}

	static void Push(IntPtr L, QFramework.UILevel arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(QFramework.UILevel), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AlwayBottom(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.AlwayBottom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Bg(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.Bg);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AnimationUnderPage(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.AnimationUnderPage);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Common(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.Common);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AnimationOnPage(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.AnimationOnPage);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_PopUI(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.PopUI);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Guide(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.Guide);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Const(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.Const);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Toast(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.Toast);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Forward(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.Forward);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_AlwayTop(IntPtr L)
	{
		ToLua.Push(L, QFramework.UILevel.AlwayTop);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		QFramework.UILevel o = (QFramework.UILevel)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

