//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class QFramework_QMonoBehaviourWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(QFramework.QMonoBehaviour), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Process", Process);
		L.RegFunction("Show", Show);
		L.RegFunction("Hide", Hide);
		L.RegFunction("SendMsg", SendMsg);
		L.RegFunction("SendEvent", SendEvent);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Manager", get_Manager, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Process(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);
			QFramework.QMonoBehaviour obj = (QFramework.QMonoBehaviour)ToLua.CheckObject<QFramework.QMonoBehaviour>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			object[] arg1 = ToLua.ToParamsObject(L, 3, count - 2);
			obj.Process(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Show(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			QFramework.QMonoBehaviour obj = (QFramework.QMonoBehaviour)ToLua.CheckObject<QFramework.QMonoBehaviour>(L, 1);
			obj.Show();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Hide(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			QFramework.QMonoBehaviour obj = (QFramework.QMonoBehaviour)ToLua.CheckObject<QFramework.QMonoBehaviour>(L, 1);
			obj.Hide();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			QFramework.QMonoBehaviour obj = (QFramework.QMonoBehaviour)ToLua.CheckObject<QFramework.QMonoBehaviour>(L, 1);
			QFramework.QMsg arg0 = (QFramework.QMsg)ToLua.CheckObject<QFramework.QMsg>(L, 2);
			obj.SendMsg(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			QFramework.QMonoBehaviour obj = (QFramework.QMonoBehaviour)ToLua.CheckObject<QFramework.QMonoBehaviour>(L, 1);
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.SendEvent((IConvertible)arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Manager(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			QFramework.QMonoBehaviour obj = (QFramework.QMonoBehaviour)o;
			QFramework.IManager ret = obj.Manager;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Manager on a nil value");
		}
	}
}

