//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class QFramework_QMgrBehaviourWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(QFramework.QMgrBehaviour), typeof(QFramework.QMonoBehaviour));
		L.RegFunction("Init", Init);
		L.RegFunction("RegisterEvent", RegisterEvent);
		L.RegFunction("UnRegistEvent", UnRegistEvent);
		L.RegFunction("SendMsg", SendMsg);
		L.RegFunction("SendEvent", SendEvent);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("ManagerId", get_ManagerId, null);
		L.RegVar("Manager", get_Manager, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Init(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			QFramework.QMgrBehaviour obj = (QFramework.QMgrBehaviour)ToLua.CheckObject<QFramework.QMgrBehaviour>(L, 1);
			obj.Init();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RegisterEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			QFramework.QMgrBehaviour obj = (QFramework.QMgrBehaviour)ToLua.CheckObject<QFramework.QMgrBehaviour>(L, 1);
			object arg0 = ToLua.ToVarObject(L, 2);
			QFramework.OnEvent arg1 = (QFramework.OnEvent)ToLua.CheckDelegate<QFramework.OnEvent>(L, 3);
			obj.RegisterEvent((IConvertible)arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnRegistEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			QFramework.QMgrBehaviour obj = (QFramework.QMgrBehaviour)ToLua.CheckObject<QFramework.QMgrBehaviour>(L, 1);
			object arg0 = ToLua.ToVarObject(L, 2);
			QFramework.OnEvent arg1 = (QFramework.OnEvent)ToLua.CheckDelegate<QFramework.OnEvent>(L, 3);
			obj.UnRegistEvent((IConvertible)arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendMsg(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			QFramework.QMgrBehaviour obj = (QFramework.QMgrBehaviour)ToLua.CheckObject<QFramework.QMgrBehaviour>(L, 1);
			QFramework.QMsg arg0 = (QFramework.QMsg)ToLua.CheckObject<QFramework.QMsg>(L, 2);
			obj.SendMsg(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendEvent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			QFramework.QMgrBehaviour obj = (QFramework.QMgrBehaviour)ToLua.CheckObject<QFramework.QMgrBehaviour>(L, 1);
			object arg0 = ToLua.ToVarObject(L, 2);
			obj.SendEvent((IConvertible)arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ManagerId(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			QFramework.QMgrBehaviour obj = (QFramework.QMgrBehaviour)o;
			int ret = obj.ManagerId;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ManagerId on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Manager(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			QFramework.QMgrBehaviour obj = (QFramework.QMgrBehaviour)o;
			QFramework.IManager ret = obj.Manager;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Manager on a nil value");
		}
	}
}

