//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "assetobj";
    }
    public class Battlescene_unity
    {
        public const string BundleName = "battlescene_unity";
        public const string BATTLESCENE = "battlescene";
    }
    public class Hellowebglpanel_prefab
    {
        public const string BundleName = "hellowebglpanel_prefab";
        public const string HELLOWEBGLPANEL = "hellowebglpanel";
    }
    public class Image_prefab
    {
        public const string BundleName = "image_prefab";
        public const string IMAGE = "image";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SCENERES = "sceneres";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string SPRITEATLAS = "spriteatlas";
    }
    public class Testimage_png
    {
        public const string BundleName = "testimage_png";
        public const string TESTIMAGE = "testimage";
    }
    public class Webgltesttexture_png
    {
        public const string BundleName = "webgltesttexture_png";
        public const string WEBGLTESTTEXTURE = "webgltesttexture";
    }
}
