// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TravelStory
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:98539de6-eef0-4182-8e00-e2fddecde6c8
    public partial class UIKitTestPanel2
    {
        
        public const string NAME = "UIKitTestPanel2";
        
        private UIKitTestPanel2Data mPrivateData = null;
        
        public UIKitTestPanel2Data Data
        {
            get
            {
                return mData;
            }
        }
        
        UIKitTestPanel2Data mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIKitTestPanel2Data());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            mData = null;
        }
    }
}
